services:
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,PLAINTEXT_HOST://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    ports:
      - "9092:9092"
      - "29092:29092"

  spark-master:
    image: apache/spark:3.5.1
    container_name: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    volumes:
      - ./spark_app:/app
      - ./delta_lake:/app/delta
    ports:
      - "8080:8080"
      - "7077:7077"

  spark-worker:
    image: apache/spark:3.5.1
    container_name: spark-worker
    depends_on:
      - spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077

  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.1.0
    container_name: mlflow
    user: root
    ports:
      - "5001:5000"
    volumes:
      - ./mlflow_data:/app
    environment:
      - GUNICORN_CMD_ARGS=--forwarded-allow-ips=* --timeout 120
    entrypoint: ["/bin/sh", "-c", "mkdir -p /app/artifacts && chmod -R 777 /app && mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:////app/mlflow.db --default-artifact-root file:///app/artifacts"]

  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyter-spark
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./delta_lake:/app/delta
      - ./mlflow_data/artifacts:/app/artifacts
      - .:/data
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=bigdata
    user: root
    entrypoint: >
      sh -c "pip install kafka-python delta-spark==3.1.0 mlflow &&
             start-notebook.sh"

  producer:
    build: ./producer
    container_name: python-producer
    depends_on:
      - kafka
    volumes:
      - ./producer:/app
      - .:/data
    environment:
      - KAFKA_BROKER=kafka:9092
    restart: always
